In [ ]:
#a linear Regration model
#This is for a multiple linear regression

In [2]:
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score #what is the use of the library

In [3]:
# proccessing data
df=pd.read_csv("house prices.csv")
df
# data=df.isnull()
# print(data.sum(False))

Square_Footage  Number_of_Bedrooms  Number_of_Bathrooms  Year_Built  \
0              1500                   3                    2        2005   
1              1200                   2                    1        1998   
2              2000                   4                    3        2010   
3              1800                   3                    2        2008   
4              1600                   3                    2        2006   
..              ...                 ...                  ...         ...   
490            1400                   3                    1        2003   
491            2100                   4                    3        2011   
492            1100                   2                    1        1997   
493            1750                   3                    2        2007   
494            1650                   3                    2        2006   

     House_Price  
0         250000  
1         180000  
2         350000  
3         300000  
4         270000  
..           ...  
490       230000  
491       380000  
492       165000  
493       295000  
494       275000  

[495 rows x 5 columns]

In [9]:
# creating indepedent and depedent valiables
X=df[["Square_Footage","Number_of_Bedrooms"]].values
y=df[["House_Price"]].values
X.reshape(-1,1)
y.ravel()
X=(X-X.mean())/X.std()
print(X.reshape(-1,1))
print(y.reshape(-1,1))

[[ 0.82122589]
 [-0.95575578]
 [ 0.46511734]
 [-0.95694281]
 [ 1.41474014]
 [-0.95456875]
 [ 1.17733444]
 [-0.95575578]
 [ 0.93992874]
 [-0.95575578]
 [ 0.22771163]
 [-0.95694281]
 [ 1.65214584]
 [-0.95456875]
 [ 1.05863159]
 [-0.95575578]
 [ 0.58382019]
 [-0.95694281]
 [ 1.29603729]
 [-0.95456875]
 [ 0.70252304]
 [-0.95575578]
 [ 1.53344299]
 [-0.95456875]
 [ 0.34641448]
 [-0.95694281]
 [ 1.11798301]
 [-0.95575578]
 [ 0.99928016]
 [-0.95575578]
 [ 0.82122589]
 [-0.95575578]
 [ 0.46511734]
 [-0.95694281]
 [ 1.41474014]
 [-0.95456875]
 [ 1.17733444]
 [-0.95575578]
 [ 0.93992874]
 [-0.95575578]
 [ 0.22771163]
 [-0.95694281]
 [ 1.65214584]
 [-0.95456875]
 [ 1.05863159]
 [-0.95575578]
 [ 0.58382019]
 [-0.95694281]
 [ 1.29603729]
 [-0.95456875]
 [ 0.70252304]
 [-0.95575578]
 [ 1.53344299]
 [-0.95456875]
 [ 0.34641448]
 [-0.95694281]
 [ 1.11798301]
 [-0.95575578]
 [ 0.99928016]
 [-0.95575578]
 [ 0.82122589]
 [-0.95575578]
 [ 0.46511734]
 [-0.95694281]
 [ 1.41474014]
 [-0.95456875]
 [ 1.17733

In [31]:
# split Data into Training and Testing set
#X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3,random_state=42)
X_train.reshape(-1)
y_train.reshape(-1)
X_test.reshape(-1)
y_test.reshape(-1)


array([400000, 295000, 230000, 230000, 300000, 320000, 150000, 230000,
       150000, 320000, 275000, 270000, 230000, 165000, 380000, 270000,
       250000, 250000, 350000, 150000, 380000, 350000, 320000, 165000,
       300000, 300000, 285000, 295000, 350000, 200000, 300000, 180000,
       150000, 350000, 350000, 270000, 295000, 350000, 165000, 165000,
       250000, 295000, 300000, 275000, 250000, 380000, 180000, 200000,
       320000, 250000, 270000, 320000, 165000, 165000, 300000, 230000,
       285000, 230000, 270000, 350000, 320000, 320000, 380000, 295000,
       250000, 300000, 165000, 230000, 270000, 285000, 400000, 165000,
       250000, 320000, 200000, 150000, 400000, 300000, 285000, 320000,
       300000, 250000, 380000, 285000, 285000, 270000, 230000, 400000,
       400000, 380000, 350000, 380000, 250000, 295000, 250000, 275000,
       400000, 270000, 320000, 275000, 380000, 285000, 165000, 270000,
       295000, 350000, 250000, 295000, 230000, 300000, 250000, 200000,
      

In [32]:
#data normalization# split Data into Training and Testing set
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3,random_state=42)

scaler =StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)
X_train.shape
y_train.shape

(346, 1)

In [33]:
#now creating a training model 
model=LinearRegression() # this is where you now apply the linearRegratision model.
model.fit(X_train,y_train)

# cheaking for the coeff & intercept 
print (f"Intercept:{model.intercept_}")
print (f"Cofficient:{model.coef_}")

Intercept:[6362889.07744737]
Cofficient:[[ 163020.45178859 6537842.66612275]]


In [34]:
# making a prediction 
y_pred =model.predict(X_test)
print(y_pred)

[[391402.30688094]
 [296562.23599799]
 [228833.76299518]
 [228833.76299518]
 [306237.73214125]
 [333349.33002139]
 [143669.1882555 ]
 [228833.76299518]
 [143669.1882555 ]
 [333349.33002139]
 [277211.24371147]
 [267535.74756822]
 [228833.76299518]
 [163020.18054201]
 [372051.31459442]
 [267535.74756822]
 [248184.7552817 ]
 [248184.7552817 ]
 [352700.32230791]
 [143669.1882555 ]
 [372051.31459442]
 [352700.32230791]
 [333349.33002139]
 [163020.18054201]
 [306237.73214125]
 [306237.73214125]
 [286886.73985473]
 [296562.23599799]
 [352700.32230791]
 [201722.16511504]
 [306237.73214125]
 [182371.17282853]
 [143669.1882555 ]
 [352700.32230791]
 [352700.32230791]
 [267535.74756822]
 [296562.23599799]
 [352700.32230791]
 [163020.18054201]
 [163020.18054201]
 [248184.7552817 ]
 [296562.23599799]
 [306237.73214125]
 [277211.24371147]
 [248184.7552817 ]
 [372051.31459442]
 [182371.17282853]
 [201722.16511504]
 [333349.33002139]
 [248184.7552817 ]
 [267535.74756822]
 [333349.33002139]
 [163020.180

In [35]:
# calculate the performance metrics
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

print(f"mean squared error:{mse:.2f}")
print(f"R2 score:{r2:2f}")


mean squared error:31108195.55
R2 score:0.993783
